#!/bin/sh

# keybinds
pgrep -x sxhkd > /dev/null || sxhkd &

# config
bspc monitor -d I II III IV V # VI VII VIII IX X

bspc config window_gap           5
bspc config border_width         3
bspc config focused_border_color '#121212'
bspc config normal_border_color '#999999'
bspc config top_padding 38

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config merge_overlapping_monitors true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc rule -a feh state=floating
bspc rule -a Zathura state=tiled

bspc rule -a blink state=floating border=off
bspc rule -a krunner state=floating border=off
bspc rule -a plasmashell state=floating border=off

bspc config external_rules_command ~/.config/bspwm/external_rules

# startup applications
# autorandr -c &
killall picom; picom -b &
