#!/bin/sh
wid=$1
class=$2
case "$class" in
  *)
    case "$(xprop -id "$wid" | awk '/WM_WINDOW_ROLE/ {print $3}')" in
            '"pop-up"' )
                    echo state=floating border=off
                    ;;
    esac
    ;;
esac
